baseurl = "https://fin-eng.github.io/blog/"
publishDir = "docs"
title = "My Rates Notebook."
canonifyurls = true
paginate = 10
theme = "startbootstrap-clean-blog"
languageCode = "en-us"
copyright = "Code released under the Apache 2.0 license."
googleAnalytics = "UA-123-45" # delete or comment to disable Google Analytics JS generation
disqusShortname = "oliverkahl" #delete or comment to disable Disqus comments

smartDashes = true

[taxonomies]
  tag = "tags"
  category = "categories"
  series = "series"

[author]
  name = "Oliver Kahl"

[params]
  DateForm = "Mon, Jan 2, 2006"
  Description = "Sharing my thoughts on Rates, Trading, Derivatives, XVA, Python"
  Author = "Oliver Kahl"
  email = "oliverkahl@gmx.de" #Remove this line if you would prefer not to use an email button in the footer.
  postSummariesFrontPage = 4 #Number of post summaries to show on front page, comment out to allow default(4)
  showReadTime = false #set to false to exclude read time from header of post

[[params.social]]
  title = "twitter"
  url = "https://twitter.com/"
[[params.social]]
  title = "github"
  url = "https://github.com/"
[[params.social]]
  title = "linkedin"
  url = "https://www.linkedin.com/"
[[params.social]]
  title = "xing"
  url = "https://www.xing.com/"

[[menu.main]]
  name = "home"
  url = "/"
  weight = -200
[[menu.main]]
  name = "Archives"
  url = "/post/"
  weight = -180
