+++
date = "2018-05-26T12:54:17+02:00"
tags = ["Swaptions", "Python", "Cash vs. Physical"]
title= "Collateralized Cash Price --- An introduction to the new settlement standard in Swaptions"
description = "Collateralized Cash Price will be effective on 1st of July 2018. We discuss what has to be done to be well prepared."
series = ["Cash vs. Physical Swaptions"]
+++
= Collateralized Cash Price - An introduction to the new settlement standard in Swaptions
:source-highlighter: coderay
:source-language: python
:imagesdir: /Users/Olli/Blog_Artikel/
Oliver Kahl <oliverkahl@gmx.de>
2017-12-14

== Overview

For years the `Euro Swaption Market` was split into two major types of
settlement methods: one being `Physical` and the other one being a cash
settlement based on an `Internal Rate of Return (IRR)`. The latter was
causing that many serious valuation problems recently that a new
market standard will be established effective from 1st of July 2018
onwards, where the IRR will be "swapped" for a discount rate
associated with collateralized swap contracts: a `Collateralized Cash
Price (CCP)`. But let's see what the problem is with the IRR and why
the CCP perfectly suits into a world of mandatory collaterlization and
clearing and therefore mimics a physical settlement quite closely.

== What is the difference between physical and cash IRR settlement and why is the latter causing trouble?

Let's firstly turn our attention to the physical settlement of
swaptions because probably the most natural way of thinking about
swaptions is, when they put into existence one of the most traded
derivatives contracts in global markets: a fixed vs. float interest
rate swap. Typically the whole valuation machinery in financial
institutions rests on swap curves which are physical by their very
definition. Building an infrastructure for interest rate options on
top of that layer is a quite straight-forward thing to do. Once up and
running, our curves projects variable cash-flows out in the future by
a forward estimation curve, while those variable cash-flows are
discounted to today together with the already fixed cash-flows with
another swap curve, the so called discount curve. In essence that
means, in the physical world, we are perfectly consistent: all swaps
and physical swaptions are valued with respect to the term
structure in all relevant swap curves.

Turning to the IRR approach now, yields something significantly
different: The swaption value at expiry is just determined by one
single swap rate observation. That observation is input for the
annuity or payoff as well as the discounting and therefore ignores any
term structure in swap curves. Or more precisely, the IRR approach has
just one term-structure: a -- and just this single -- flat swap curve.

Therefore we must acknowledge that cash settled swaptions based on an
IRR have an underlying that is different to the swaps we are generally
referring to. Although correlation between the two is high, strictly
speaking our IRR swap compared to the (physical) swap has to be
modeled separately to capture it's unique dynamics.

== But why has one come up with such a "distorting" convention in the first place?

For this we fast forward things to the expiry of the IRR swaption and
see that things get pretty easy with the IRR methodology: all
we have to know is the swap rate fixing and a bit of plug & chug into
the IRR formula (PV function in Excel for instance). Very convenient
thing to do, so no discussion to arrive at the correct settlement
amount.  And to be fair, valuation differences ignoring the speciality
of the IRR swaption tend to be limited. So probably the IRR method was
initially agreed, to make a settlement easy, while ignoring or
tolerating a "small" valuation issue.

== Why is the market now deciding to move to CCP?

There are quite a bunch of arguments around suggesting that
move: Firstly, since 2008 the market focuses much more on "correctly"
discounting cash-flows, by reflecting credit, funding and collateral
involved in derivatives transactions. In that spirit, a CCP is more in
line with current market standards. Another argument is a steep swap
curve (where valuation differences are particular strong), and at the
same time a low rates environment where dealers see many receiver
swaptions deeply in-the-money. Especially those swaptions already
substantially in-the-money cause severe valuation issues pushing bid/
offer spreads to untypically wide levels. Finally, more recent theory
suggests that arbitrage is not only possible (as it was seen before)
with trading in CMS style products, but also in vanilla products (i.
e. swaption collars). A quite active market in zero-wide-collars --
often traded with one collar settling IRR and the other physical --
further support this argument. In that context switching standards is
probably kind of "overdue" and finally was decided by ISDA and global
dealers.

== How does the CCP compare to physical settlement?

CCP mimics how valuation for the majority of physical swaps is done.
Therefore the settlement amount due -- according to CCP -- is simply the
value of the physical swap literally the second when the options
holder opts into exercising the swaption and thereby instantiating the
swap. Basically, it is expected that there will be no pricing
differences between CCP and physical settlement as long as those
contracts are traded under a market standard collateral agreement.
Documents are structured in a way that certain adjustments are
possible with regards to some specialities in collateral agreements.
But as soon as those documents are not in place or business remains
uncollateralized things get complicated again: typically that is the
moment where an XVA desk comes into play. But even in this more
complex situation, it is an advantage to have the risk-free benchmark
calculated accurately and then adjust for all the "va's" afterwards.

== What will happen to the old IRR Swaptions? Will there still be a market for them?

So far global dealers seem committed to further support the market for
IRR style swaptions. It has to be seen how strong this commitment is
and whether the market will dry up over a medium- or long term.

== What has to be done to be ready for the switch?

That largely depends on where your swaption business is standing. We
will therefore make case separations for three types of swaption
businesses.

*+++<u>Case 1:</u>+++ Large book of physical, cash IRR, and CCP swaptions perspectively with
already consistent valuation of IRR cash/ physical basis*

That is the typical setup for a medium to big institution where
valuation is already consistent for all products. Here the
adjustment with the new market standard merely boils down to
maintenance works. For example, calibration inputs are probably
focused at IRR swaption at the moment because of the highest liquidity
in that space. So probably that will be fed perspectively from CCP data
sources as liquidity is expected to move to the new standard.

*+++<u>Case 2:</u>+++ Large book of physical, cash IRR, and CCP swaptions perspectively with
IRR cash/ physical basis not implemented*

That's probably where most options approaching this lie. All of them
have in common that they will incur some PnL effects sooner or later.

One option might be to trade out of cash IRR swaptions in advance or
in the transition to spare implementation of a consistent framework.
Afterwards input data can be simply switched to the new framework and
consistency will be achieved for future trades. However, depending on
the size of the legacy book and the moneyness of those trades that can be
difficult or costly in terms of what is quoted away from mid by
dealers.

Another option on the menu might be holding on to the legacy book,
while establishing a consistent pricing framework for legacy trades as
well as new trades. That carries some implementation costs but saves
trading cost on closing positions on legacy trades. Potentially a more
medium- or long-term strategy to get out of IRR swaptions can be
attached to it as well.

One more opportunity might be utilizing providers for switching old IRR
swaptions into new CCP swaptions. But at the moment those services
are still in their infancy and it has to be seen how effective those
will turn out to be.

*+++<u>Case 3:</u>+++ Book of physical swaptions only, intending to solely trade those in the
future*

The seemingly not affected use-case. Looking a bit under the hood
that assumption might turn out to be wrong. Typically an institution will still
value their physical swaptions based on IRR swaption volatilities
because those are associated with being the most liquid grid of input
data. Once that is changed to CCP, valuation will move and therefore
an effect can be seen. But probably the way to go in that scenario is
to just take that one-off effect. Still, timing of the effect might be
steerable if one holds on feeding IRR volatility from legacy sources.

== How does a consistent valuation in a book with Physical, IRR and CCP Swaptions look like?

That will be the main focus of the next articles in this series.
Basically, we will do this in three steps:
Firstly, we lie the foundation by obtaining and formatting the
needed data. Step two is the heavy lifting, where we calibrate the
model. Last step will be utilizing a SABR framework on the calibrated
data to complete the volatility cube for all settlement styles.
